=== PHP

==== Installation Location

The default installaton folder is `server\bin\php`.

==== Working with multiple PHP versions

You can install multiple version of PHP into the `\bin` folder, e.g. `\bin\php-5.6.1` next to `bin\php`.

You might use the PHP version switcher of the webinterface to switch between versions.

The PHP version switcher does two things.
Firstly, the version number in the `bin\php` folder is determined, then the folder is renamed accordingly, e.g. `bin\php-1.2.3`.
Secondly, it renames the folder of the selected version (the one it should switch to) from `bin\php-1.2.3` to `bin\php`.

In other words: the PHP interpreter in the `bin\php` folder is the active and used one, when multiple version of PHP are installed.

Please keep in mind that configuration and installed extensions might differ!

==== What does NTS and TS mean?

NTS and TS are abbreviations for `non-thread safe` and `thread-safe`.

Both processes and threads are independent sequences of execution.
The difference is that threads (of the same process) run in a shared memory space, while processes run in separate memory spaces.

==== PHP Bitsizes

Important Note on the PHP 64bit releases

PHP 5.x provides experimental 64-bit support.

The x64 builds of PHP 5 for Windows are experimental, and do not provide 64-bit integer or large file support. 
It has has memory limitations (max. memory = 2047M). No matter the architecture, a long value is always 32bit. 
This behaviour of PHP is expected and known for a long time.

PHP 7 provides full 64-bit support.

The x64 builds of PHP 7 support native 64-bit integers, LFS, memory_limit and much more.

==== Configuration

The default configuration file for PHP is `server\bin\php\php.ini`.

===== PHP Configuration for Composer

There is a huge impact of just loading Xdebug. 
It slows the Composer run down by 3x or 4x, even when the profiling feature is not enabled.
In other words: xdebug is invaluable for debugging, but increases the memory used and processing time of Composer.
See https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer

The question is "How to disable Xdebug for Composer runs on the CLI?".
I addressed this issue by providing a seperate, minimal PHP config file.

Important: There is a seperate, minimal PHP configuration file for `Composer` runs.
Whenever you invoke `composer.bat` this minimal config for PHP will used to start Composer.
The purpose of this config is to run Composer, without xDebug in order to speed it up.


