== Software Components

=== Nginx

Nginx ("engine x") is a web server written by Igor Sysoev in 2002. It can act as a reverse proxy server for HTTP, HTTPS, SMTP, POP3, and IMAP protocols, as well as a load balancer and an HTTP cache. Nginx runs on Unix, Linux, BSD variants, OS X, Solaris, AIX, HP-UX, and Windows.
Nginx is free and open source software and released under the terms of a BSD-like license.

The default installaton folder is `server\bin\nginx`.

==== Configuration

The file `nginx.conf` in `server\bin\nginx\conf\` is the main configuration file.

The stack ships also a very minimal configuration for debugging purposes: https://github.com/WPN-XM/software/blob/master/nginx/config/nginx.conf.debug[`nginx.conf.debug`].

==== Server Blocks (domains-enabled and domains-disabled)

This config file includes other configuration files from the folder `server\bin\nginx\conf\domains-enabled`. These configuration files are mostly server blocks. They contain Nginx configuration directives to serve specific PHP applications correctly and support their URL rewrite rules, which are needed to enable nice looking URLs without parameters.

The server stack ships several server blocks by default in the folder `server\bin\nginx\conf\domains-disabled`. To use one of these files, simply move or copy them to the `server\bin\nginx\conf\domains-enabled` folder and restart Nginx. The new server block configuration is then automatically included.

The configs are also on Github: https://github.com/WPN-XM/software/tree/master/nginx/config/conf/domains-disabled

==== root and server_name

The most important directives in a server block are `root` and `server_name`, next to the configuration of the rewrite rules for the specific application.

The `root` directive defines a relative path to the project, e.g. `www/<my_project_folder>`.
But a hardcoded path will work too, e.g. `c:\server\www\my_project_folder`.
The `server_name` directive defines which server block is used for a given request.

A very basic example for Wordpress: `root www/wordpress` and `server_name wordpress.dev`.
This makes Wordpress available at the URLs http://localhost/wordpress and http://wordpress.dev.
The URL http://wordpress.dev needs an additional entry in your `hosts` file. So, don't forget to adjust your `hosts` file accordingly!

=== Pickle

Pickle is a cross-platform PHP Extension installer.

==== Usage

For example, to install the memcache extension run the following command:

[source,shell]
----
$ pickle install memcache
----

Its also possible to require a specific version:

[source,shell]
----
$ pickle install <extension>@<version>
----