=== Go Git Service (gogs)

Go Git Service is a self-hosted Git service written in Go.

* Website: https://gogs.io/
* Documentation: https://gogs.io/docs

==== Installation Location

The default installaton folder is `server\bin\gogs`.

==== Configuration

The custom user configuration file is located at `\server\bin\gogs\custom\conf\app.ini`.

There is also a main configuration file located at `\server\bin\gogs\conf\app.ini`.

Do not modify the main config. Make your modifications to the custom config.
The user config values replace any prior values from the main config.
That allows a seemsless updates to new Gogs versions, 
which might ship new configuration directives in their new main config file .

==== Running Go Git Service

=== Server

By default the server runs at http://localhost:3000/

=== Nginx Server Block

The is a default Nginx server block configuration file `go-git-service.conf`.
Nginx will accept requests at `http://gogs.dev` forwarding them to `http://localhost:3000/` internally.

=== As a Windows Service

