[NOTE]
.This document is under active development and discussion!
====
If you find errors or omissions in this document, please don't hesitate to {uri-wpnxm-github-issues}[submit an issue or open a pull request] with a fix.
====

[preface]
== Preface

The WPN-XM server stack is a software bundle for web developers
and a profound base for the development of web applications.

This book is a comprehensive guide to getting started and working with WPN-XM.
It includes details of the installation, the architecture, folder layout and 
the different applications shipped and their default configurations.

WPN-XM provides a number of advantages:

* multiple installers
  - the prepackaged installers ship software components as a bundle
  - the webinstaller allows the selection of components to download
* two software catalogs to chose applications from
  - Stack components 
  - PHP applications
* all components are also available for selective manual download on our website
* the updater 
  - indicates updates for installed software components
  - allows to keep your stack up-to-date by updating already installed components
  - allows to install additional (not-yet-installed) components
* it is a preconfigured development environment, ready to work out-of-the-box
* Sever Control Panel
* Webinterface
* fully Open-Source
  - build using an open-source build toolchain
  - providing reliable and continous open-source builds

WPN-XM has several goals:

* convenient local web development environment with a focus on PHP
* simple and fast installation
* out-of-the-box configuration for servers
* simple start and stop of servers
* easy to start new projects
* support for multiple user projects
* seamless automatic updates

== Reasons

There are already several server stacks for Windows out there.
Why another one?

Just to name a few reasons:

* Well, a PHP server stack like i imagined didn't exist (until now :). 
* I love tooling and making things. Things which actually make it easier, to make new shiny web tech things.
* Mainly because installing things on Windows isn’t straightforward.
  I wanted to save my life-time and the life-time of other developers by getting rid of the daunting, 
  repeated tasks of searching for software and installing stuff manually.
  I imagined to build an environment, where pulling in new web development related packages and tools is easy.
  A system where all the hassle of settings things up is greatly reduced and everything is ready to work right out-of-the-box.
  The stack addresses the fundamental problem of Windows: the missing package management.
  But, only for a small subset of the software ecosystem: for software, relevant for web developers. 
* I started the project as a true open-source project, because other server stacks were (and are still) not really open-source.
* The project solves the i'm not in charge and cannot modify the project like i want problem. 
* I'm trying to close the gap between third-party vendors, which provide tools and servers, and PHP.
  Mainly, because PHP's support for these `niche` DB system is pretty bad.
  Example-wise, let's take a look at DB vendors: 
  The combination of PHP and MySQL as RDBMS helped PHP to get used in lots of places and use-cases.
  But, nowadays, there are other interesting database solutions out there,
  including NOSQL, Graph, RDF and realtime databases.
* Finally, let's partly quote the auto maker Renault: i need to "drive the change".