=== PHP

==== Installation Location

The default installaton folder is `server\bin\php`.

==== Working with multiple PHP versions

You can install multiple version of PHP into the `\bin` folder, e.g. `\bin\php-5.6.1` next to `bin\php`.

You might use the PHP version switcher of the webinterface to switch between versions.

The PHP version switcher does two things.
Firstly, the version number in the `bin\php` folder is determined, then the folder is renamed accordingly, e.g. `bin\php-1.2.3`.
Secondly, it renames the folder of the selected version (the one it should switch to) from `bin\php-1.2.3` to `bin\php`.

NOTE: The PHP interpreter in the `bin\php` folder is the active and used one, when multiple version of PHP are installed.

IMPORTANT: Please keep in mind that configuration and installed extensions might differ!

==== What does NTS and TS mean?

NTS and TS are abbreviations for `non-thread safe` and `thread-safe`.

Both processes and threads are independent sequences of execution.

The difference is that threads (of the same process) run in a shared memory
space, while processes run in separate memory spaces.

Code is thread-safe, when modifications of data structures in the shared memory
are guaranteed to be safely executed from multiple threads. A safe execution is
achieved by avoiding race-conditions and deadlocks,  for instance, by means of
synchronization between the threads. A deadlock occurs when many processes
execute no further because they are waiting for a shared resource, which is
being used and held by another process.

==== PHP Bitsizes

[IMPORTANT]
====
Note on the PHP 64bit releases:

PHP 5.x provides experimental 64-bit support.

The x64 builds of PHP 5 for Windows are experimental, and do not provide 64-bit integer or large file support. 
It has has memory limitations (max. memory = 2047M). No matter the architecture, a long value is always 32bit. 
This behavior of PHP is expected and known for a long time.

PHP 7 provides full 64-bit support.

The x64 builds of PHP 7 support native 64-bit integers, LFS, memory_limit and much more.
====

==== Configuration

The default configuration file for PHP is `server\bin\php\php.ini`.

[NOTE]
====
There is a minimal configuration file for Composer runs `server\bin\composer\php.composer.ini`. 
Please check the Composer chapter.
====