=== Redis

Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker. 
It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, 
hyperloglogs and geospatial indexes with radius queries. 

Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, 
and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.

* Website: http://redis.io/
* Documentation: http://redis.io/documentation
* Redis for Windows is build and provided by MSOpenTech: https://github.com/MSOpenTech/redis

==== Installation Location

The default installaton folder is `server\bin\redis`.

==== Configuration

Redis config is located at `\server\bin\redis\redis.conf`. 

==== Working with Redis from PHP

Redis is an independent server, which can be called by any other process. 
This calls for a bridge between the calling process and the Redis service.

In other words: you need a PHP client to interact with Redis.
This client is either a PHP extensions or a PHP library.

There are several to chose from: http://redis.io/clients#php

===== PHP extension

There is a redis client written in C as a PHP extension.

- https://github.com/phpredis/phpredis
- https://pecl.php.net/package/redis 

===== PHP library

You need a PHP library to interact with Redis.

There are several to chose from:

- https://github.com/amphp/redis
- https://github.com/cheprasov/php-redis-client
- https://github.com/nrk/predis
- https://github.com/Shumkov/Rediska
- https://github.com/colinmollenhour/credis
- https://github.com/ptrofimov/tinyredisclient

==== Working with Redis from Node

A redis client for for Node.js is Mranney's "Node Redis".
 - https://github.com/NodeRedis/node_redis 

==== Administration Tools for Redis

There are several administration tools for Redis available:

[horizontal]
Redisk Desktop Manager::        https://redisdesktop.com/download
                                https://github.com/uglide/RedisDesktopManager/releases
Redis-Commander for Node/NPM::  https://github.com/joeferner/redis-commander
FastoRedis::                    https://fastoredis.com/
PHPRedisAdmin::                 https://github.com/erikdubbelboer/phpRedisAdmin

==== Redis compared to Memcached

Both Redis and Memcached are data cache systems and open source. 
Redis allows to store abstract data types, while Memcached stores only strings. 
Redis has snapshotting and journaling capabilites, which means that saved data stays even after a system restart, 
while Memcache's memory stored-data is lost. Memcached is basically a memory store for short-lived data. 
Redis provides several fine-tuning options and features like advanced memory management and a better data eviction control.
