=== PostgreSQL

PostgreSQL is an object-relational database management system (ORDBMS) based on POSTGRES, Version 4.2, developed at the University of California at Berkeley Computer Science Department. POSTGRES pioneered many concepts that only became available in some commercial database systems much later.

[horizontal]
Website::                                           https://www.postgresql.org/
Docs for Current Stable Version::                   https://www.postgresql.org/docs/current/static/index.html

==== Connection data

The most GUI applications will expect you to provide the following connection parameters to connect:

[horizontal]
Host::      localhost
Port::      5432 (default)
Username::  root
Password::  blank
Database::  yourdb

If you need to provide an URL, use `postgresql://username@localhost/yourdb`.

[IMPORTANT]
====
**Username**

WPN-XM versions below v0.8.7 did not set a username during the installation and initial setup of PostgreSQL with `initdb`.
For these installs `initdb` created a table named "postgres" owned by user "current logged in user name", 
which is/was the user running the installer. 
When calling commands  on the CLI, please leave the `-U` or `--username` CLI arguments away, so that the default username is used.


Starting with WPN-XM 0.8.7 the default username is "root". 
When calling commands  on the CLI, please use `-U root` or `--username=root` .
====

==== First steps after installation

Please use the interactive terminal application `pgsql` to make your first steps.

You find detailed instructions in the PostgreSQL manual (https://www.postgresql.org/docs/current/static/app-psql.html).

1. Switch to the folder `c:\server\bin\pgsql`
2. run `psql --version` to show the version
3. run `psql --list -U root` to list the databases

```
                                        Liste der Datenbanken
   Name    | Eigentümer | Kodierung |    Sortierfolge     |     Zeichentyp      | Zugriffsprivilegien
-----------+------------+-----------+---------------------+---------------------+---------------------
 postgres  | root       | UTF8      | German_Germany.1252 | German_Germany.1252 |
 template0 | root       | UTF8      | German_Germany.1252 | German_Germany.1252 | =c/root            +
           |            |           |                     |                     | root=CTc/root
 template1 | root       | UTF8      | German_Germany.1252 | German_Germany.1252 | =c/root            +
           |            |           |                     |                     | root=CTc/root
(3 Zeilen)
```

4. run `psql --username=root --dbname=postgres` to edit the postgres table using the interactive console


```
c:\server\bin\pgsql\psql --username=root --dbname=postgres
 psql (9.6.0)
 Type "help" for help.
```

Run `help`:

```
postgres=#  help
 You are using psql, the command-line interface to PostgreSQL.
 Type:  \copyright for distribution terms
        \h for help with SQL commands
        \? for help with psql commands
        \g or terminate with semicolon to execute query
        \q to quit
```

==== Support for JSON and JSONB

The storage format for `json` is plain text format, while it is a binary representation for `jsonb`.

It takes more time to create the binary representation from the input representation (jsonb is slower, than json).
and it takes more disk space to store than `json` (jsonb uses more space, than json).

The parsing of `json` has to be repeated, for each operation at a json value.

`json` operations take significantly more time than `jsonb`. 
In other words: `jsonb` is faster for operations on JSON value(s).

To sum up:

[IMPORTANT]
====
*When to use JSON or JSONB?**

Use JSON, if you only work with the JSON representation in your application, which is stored and retrieved.
Use JSONB, if you do a lot of operations on the JSON value(s), or use indexing on some JSON field.
====

==== GUI Clients

The official GUI client is pgAdmin and ships with PostgreSQL. 
But there are many GUI clients for PostgreSQL. 
You can find many of them in the https://wiki.postgresql.org/wiki/Community_Guide_to_PostgreSQL_GUI_Tools
[Community Guide to PostgreSQL GUI Tools] in the PostgreSQL wiki.

[horizontal]
Datagrip::                  https://www.jetbrains.com/datagrip/
Datazenit::                 https://datazenit.com/
DBeaver::                   http://dbeaver.jkiss.org/
DbVisualizer::              https://www.dbvis.com/
Navicat for PostgreSQL::    http://www.navicat.com/products/navicat-for-postgresql
pgAdmin::                   http://pgadmin.org/
Valentina Studio::          http://www.valentina-db.com/en/
DBGlass::                   http://dbglass.web-pal.com/
