=== Getting Help

There are several channels to reach the developers and the WPN-XM  community to
get direct assistance.

To find the right answers to your questions, you can turn to one of the
following sources to get help and discuss your issues, 
but also to receive news and update notifications.

**Github Issues**

If you want to report a bug or contribute your ideas, you can use the 
https://github.com/WPN-XM/WPN-XM/issues[WPN-XM Issue tracker on Github].

**Twitter**

Follow https://twitter.com/wpnxm[WPN-XM on Twitter] to get real-time news 
regarding the development and to receive news and update notifications.

**Forum**

You might also join the https://forum.wpn-xm.org/[WPN-XM community forums], 
where you can ask the community for help or report bugs and contribute ideas.

**Stack Overflow**

Scala is an http://stackoverflow.com/questions/tagged/wpn-xm[active topic] 
on Stack Overflow, a very popular programmer Q&A site.

**Gitter

Gitter is a chat tool that is tightly coupled with GitHub.  If you don't already
have one, you will need to create a free GitHub account.  Once done, you can
access the chat at https://gitter.im/WPN-XM/WPN-XM  or you can download one of
the available Gitter apps.

**Google+**

We have an https://plus.google.com/u/0/communities/109388403943670810388[Google+ community] 
that is a good place to discuss and learn about WPN-XM.

**Mailing List**

We also have a low-volume https://groups.google.com/forum/#!forum/wpn-xm[mailing list].