=== MongoDB

MongoDB (from humongous) is a free and open-source cross-platform document-oriented database. 
It's a popular http://en.wikipedia.org/wiki/NoSQL[NoSQL] database.

[IMPORTANT]
====
**32-bit Limitations**

The 32-bit versions of MongoDB have the following limitations:

* no support for the WiredTiger storage engine,
* disabled journaling, because journaling further limits the maximum amount of data that the database can store,
* the total storage size for the server, including data and indexes, is 2 gigabytes. 
  For this reason, do not deploy MongoDB to production on 32-bit machines.

If you’re running a 64-bit build of MongoDB, there’s virtually no limit to storage size. 
For production deployments, 64-bit builds and operating systems are strongly recommended. 

See http://blog.mongodb.org/post/137788967/32-bit-limitations[here] for more information.
====

[horizontal]
Website::        https://www.mongodb.org/
Documentation::  https://docs.mongodb.org/manual/

Please check http://docs.mongodb.org/manual/tutorial/getting-started/[MongoDB's Getting Started guide] for more!

==== PHP Extension for Mongo

To access MongoDB from PHP you need two things:

the MongoDB server `mongod` running and the PHP driver installed.

[NOTE]
====
[horizontal]
Website::             http://pecl.php.net/package/mongodb
Docs::                https://docs.mongodb.org/ecosystem/drivers/php/
PHP Driver Source::   https://github.com/mongodb/mongo-php-driver
Issues::              https://jira.mongodb.org/browse/PHPC
PHP API::             http://php.net/mongodb
====

===== Driver Compatibility

The old and legacy MongoDB PHP driver is `mongo`, while the new driver is `mongodb`.
For a detailed overview please see the 
https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#php-driver-compatibility[PHP Driver Compatibility Table].

==== Default Port

The default port for MongoDb is `27017`.

https://docs.mongodb.com/manual/reference/default-mongodb-port/
