=== Requirements

WPN-XM is designed to work on a wide range of computers. 
This section provides basic guidelines to ensure your WPN-XM experience is as smooth as possible.

==== Which Windows versions are supported by your installation wizards?

You can execute our installation wizard executables on nearly all Windows versions.

The installation wizards are Inno-Setup based.
Inno-Setup supports every Windows release since 2000, including:
Windows Server 2003, 2008, 2008 R2, 2012 and, Windows 2000, XP, Vista, 7, 8, 8.1, 10 . 
The installers do not require service packs.

==== Which Windows versions are supported by the packaged components?

We differentiate installers by bitsize.
We build installers for x86 and x64 Windows versions and bundle components accordingly.

When bundling components our lowest supported Windows version is Windows 7.

Please take a look at the Windows compatibility of the components included in the installer.

[NOTE]
====
We test installers for compatibility only on Windows 7 and Windows 10.
==== 

[WARNING]
====
If you are running into a compatibility issue with one of the bundled components, please
do not hesitate to inform us and report the problem over at https://github.com/WPN-XM/WPN-XM/issues[Github Issues]. 
Thank you!
====

===== List of supported Windows Versions

* Windows 7 (32-Bit) Professional
* Windows 7 (64-Bit) Home Premium and Professional
* Windows 7 SP 1 (32-Bit) Home Premium, Professional, and Enterprise
* Windows 7 SP 1 (64-Bit) Home Premium, Professional, Enterprise, and Ultimate
* Windows 8 (32-Bit and 64 Bit) Core, Professional, and Enterprise
* Windows 8.1 (32-Bit and 64 Bit) Core, Professional, and Enterprise
* Windows 8.1 Update (32-Bit and 64 Bit) Core, Professional, and Enterprise
* Windows 10

==== Minimum Requirements (todo)

* OS
* Processor
* Memory
* Storage
* Additional Notes

==== Recommended Requirements (todo)

* OS
* Processor
* Memory
* Storage
* Additional Notes

<<<
