=== Composer

All our installers ship Composer out-of-the-box. 

==== Installation Location

The default installaton folder is `server\bin\composer`.

==== Configuration

The installer will set the `server\bin\composer` to the ENV PATH.

This makes `composer.bat` available system-wide.

==== Usage

To run Composer on the CLI type

`composer`.

==== PHP Configuration for Composer

Users often ask "How to disable Xdebug for Composer runs on the CLI?".

[NOTE]
====
We provide a separate, minimal PHP configuration file for `Composer` runs.
The file is named `php.composer.ini`.
Whenever you invoke `composer.bat` or run `composer` on the CLI, 
the minimal config will be used to start PHP, before Composer is started.
The purpose of this config is to run Composer, without xDebug in order to speed it up.
====

**Why?**

There is a huge impact of just loading Xdebug. 
It slows the Composer run down by 3x or 4x, even when the profiling feature is not enabled.
In other words: xdebug is invaluable for debugging, but increases the memory used and processing time of Composer.
See https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer

==== Official Windows Installer

[NOTE]
====
The server stack doesn't use the official 
https://github.com/composer/windows-setup/releases/[Windows Installer].

Further instructions for Composer’s Windows installer can be found within the 
https://github.com/composer/windows-setup/blob/master/README.md[README].
====
