=== PostgreSQL

PostgreSQL is an object-relational database management system (ORDBMS) based on POSTGRES, Version 4.2, developed at the University of California at Berkeley Computer Science Department. POSTGRES pioneered many concepts that only became available in some commercial database systems much later.

https://www.postgresql.org/[Website]
https://www.postgresql.org/docs/current/static/index.html[Documentation for Current Stable Version]

==== Support for JSON and JSONB

The storage format for `json` is plain text format, while it is a binary representation for `jsonb`.

It takes more time to create the binary representation from the input representation (jsonb is slower, than json).
and it takes more disk space to store than `json` (jsonb uses more space, than json).

The parsing of `json` has to be repeated, for each operation at a json value.

`json` operations take significantly more time than `jsonb`. 
In other words: `jsonb` is faster for operations on JSON value(s).

To sum up:

[IMPORTANT]
====
*When to use JSON or JSONB?**

Use JSON, if you only work with the JSON representation in your application, which is stored and retrieved.
Use JSONB, if you do a lot of operations on the JSON value(s), or use indexing on some JSON field.
====

==== GUI Clients

The official GUI client is pgAdmin and ships with PostgreSQL. 
But there are many GUI clients for PostgreSQL. 
You can find many of them in the https://wiki.postgresql.org/wiki/Community_Guide_to_PostgreSQL_GUI_Tools
[Community Guide to PostgreSQL GUI Tools] in the PostgreSQL wiki.

Datagrip[https://www.jetbrains.com/datagrip/]
Datazenit[https://datazenit.com/]
DBeaver[http://dbeaver.jkiss.org/]
DbVisualizer[https://www.dbvis.com/]
Navicat for PostgreSQL[http://www.navicat.com/products/navicat-for-postgresql]
pgAdmin[http://pgadmin.org/]
Valentina Studio[http://www.valentina-db.com/en/]
DBGlass[http://dbglass.web-pal.com/]

==== Connection data

The most GUI applications will expect you to provide the following connection parameters to connect:

Host: localhost
Port: 5432 (default)
User: user name
Password: blank
Database: same as user name

If you need to provide an URL, use `postgresql://YOURUSERNAME@localhost/YOURUSERNAME`.
