language: ruby
install:
  - gem install asciidoctor tilt haml
  # diagram support
  #- gem install asciidoctor-diagram
  #- apt-get install dot
before_script:
  - asciidoctor --version
  - ls -alF
script:
  - asciidoctor en/book.asciidoc -o output/en/index.html
  - ls -alF output
after_success:
  - ./publish.sh
git:
  depth: 5
env:
  global:
    - secure: y+7/Ltd+JR821O81K0Ed6nqMMr8HsJkN7E081wbj/eQxrt1pVgoe8C5zYZjtp7DXwONZGY77j6940hsIx5HsdV6B/C4ollefloz++T2f9gaVAfsejb67l8m35NScs5YQO3QveIPmHaGY8wP6fFkGTdbv+tBO4/cHt1fGifivovOJHLIUmu3I9IGNZNN4kHeu1dNJ5FytHlHlnJgY3r8wCc3qlMA9iGCPYlgoF5dR7MDQ2Cire1xq3t5OnJ/W4kL5NkWtRMcdKhK9WoN88767+PvDPGdUUSdXQLDebVCXVWj8m6pynGo4NYjDqU4B7xa7WqgXXVz/apyMlxlQZOzcJp9TF4A9iON6vAX4gwq5N5QUrf2is1urVQgvL9I2iFZuE6GJyxgeD0lYt0hWPTNh1zF8K1ps4Se8oGWHQOuZV0M6oCqs48XbfHFBJliEOTOAKaXi+eyOQYWg1olSo6u5KY8C7OCO6MggE6GRH6N+YKkvQZiYB7XHjU6OcRKqOfXH2juhWeyC5h3GZCa7eESe92Lf5jCJ8nZ8arpXUM1fN0Wf+qCmbB4xcFJeJmBUDCh5jwTK2uiw4Mnm0WmffFh45Cyh0tzd0wN5X/K7jl0TwXOK1RRefNyOzvZXzEHZBQ7Eksib1oSFOTge1SXEVWIH6n6eXo1UcE1Y9pmBkM9HGAM=
