language: ruby

install:
  - gem install asciidoctor tilt haml

before_script:
  - asciidoctor --version
  - ls -alF

script:
  - asciidoctor en/book.asciidoc -o output/en/index.html
  - ls -alF output

after_success:
  - ./publish.sh

# reduce commit history of git checkout
git:
  depth: 5