== Website

=== Version Matrix

The version matrix for all installation wizards.

This tool helps to avoid version incompatibilities by defining stable version
sets of components, which simply work together.  It shows already released
installers, the current release and the "next" releases. Each installer has it's
own column, while each row contains a software component from our registry. 

A green box indicates, that a component is included, also showing it's version number. 

The editor allows to derive installers form already existing ones and to
update the version number of software components by using a simple dropdown. 

The blue column indicates the "latest version" from the registry.

The installer registries are saved as easy consumable JSON files.
They are used in two ways: to create the download description file, 
in order to download components for the packaged installers, 
and to provide details about the components included in a release.

=== Installer Comparison View

=== Configuration Comparison View

