== Documentation

This chapter describes our documentation toolchain.

=== AsciiDoc

We are using Asciidoc for documentation writing. AsciiDoc is a human-readable document format, 
semantically equivalent to DocBook XML, but using plain-text mark-up conventions.

We create the User-Manual and this Developer-Manual in HTML and PDF format.

The HTML output is generated by by `asciidoctor`.
The PDF output is generated by `asciidoctor-pdf`.

Diagrams are created on-the-fly by `asciidoctor-diagram` and the `ditaa` or `graphviz` renderers.

==== Using AsciiDoc

- http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Reference]
- http://asciidoctor.org/man/asciidoctor/[Asciidoctor CLI Commands]
- http://asciidoctor.org/docs/user-manual/[Asciidoctor Manual]
- https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoctor PDF Theming Guide]
- https://asciidoclive.com[AsciiDocLive - Online Editor]

=== Source Folder Layout

The source folder layout supports the translation of manuals.

=== Target Folder Layout

=== Deployment To Github Pages

The deployment to Github Pages is automated.

=== Translation

The Asciidoc files are in locale directories: `user-manual/XX/` where `XX` is language (en, fr, de, it, …​).

To start a translation, you would first make a copy of the `adoc` file source language into the target language.
For instance, when translating the Installation chapter from English to Italian, 
you would copy the English `user-manual/en/chapter01-installation.adoc` to 
`user-manual/it/chapter01-installation.adoc` and then work on it.

The translations missing in files are indicated by this string:

  // TRANSLATION MISSING

You must translate whole files, except links and special keywords for notes, warnings.
These words must be kept unchanged, because they are Asciidoc Language Syntax and affect output generation:

```
[[link_name]]
<<link_name>>
```

```
[NOTE]
[TIP]
[IMPORTANT]
[WARNING]
[CAUTION]
```

When there is a name after [link_name], then you must translate it:

 <<link_name,this text must be translated>>
