== API

You find the API documentation here: http://wpn-xm.org/api-docu/api-doc.htm

Let's go through the most important API queries: `get` and `updatecheck`:

=== Get 

https://wpn-xm.org/get.php

This is the header redirection script. The script provides a header response to
a software and version request in form of a header redirection to the download URL. 

The webinstallation wizards use these hard-coded links for downloading components.

*Example*

*Request (GET)* for latest version
```
 https://wpn-xm.org/get.php?s=nginx
```

*Request (GET)* for specific version
```
 https://wpn-xm.org/get.php?s=nginx&v=1.2.1
```

Response is a header redirection to the download URL.

=== Update Check

https://wpn-xm.org/updatecheck.php

You want to know, if you are running an old version of a software component and should update?

The `updatecheck.php` script provides a JSON response to a update-check request
for individual components of the WPN-XM Server Stack.

The script accepts two parameters `s` and `v`:

- Parameter `s` is the name of a software component.
- Parameter `v` is the version of this software component.

*Example*

*Request (GET)*
```
https://wpn-xm.org/updatecheck.php?s=nginx&v=1.2.1
```

*Respone (JSON)*
```
{
   "software" : "nginx",
   "your_version" : "1.2.1",
   "latest_version" : "1.3.7",
   "href" : "http:\/\/www.nginx.org\/download\/nginx-1.3.7.zip",
   "message" : "You are running an old version of Nginx and should update immediately."
}
```
